trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: veracode

steps:
- task: New-Veracode-PipelineScan@0
  inputs:  
    VeracodeAPIID: '$(vid)'  
    VeracodeAPISecret: '$(vkey)'
    fileToScan: '$(System.DefaultWorkingDirectory)/entrypoint.sh'  
    policyName: 'VeraDemo Policy'
    breakPipeline: true
    updateTasksVersion: true
