trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
  displayName: 'Use Python 3.x'

- script: |
    python --version
  displayName: 'Display Python version'

- script: |
    python your_script.py
  displayName: 'Run Python script'
