trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- task: pipelinescan
  displayName: 'Run Veracode scan'
  inputs:
    samplestring: 'Hello World'
