trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: veracode

steps:
- task: New-Veracode-PipelineScan@0
  inputs:  
    VERACODE_API_KEY_ID: '$(vid)'  
    VERACODE_API_KEY_SECRET: '$(vkey)'
    VERACODE_APP_ID: '$(appId)'
    VERACODE_UPLOAD_PATTERN: '$(System.DefaultWorkingDirectory)/target/verademo.war)'  
    policyName: 'VeraDemo Policy'
    breakPipeline: true
    updateTasksVersion: true
