trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: veracode

steps:
- task: Veracode-Scan@0
  inputs:  
    VeracodeAPIID: '$(vid)'  
    VeracodeAPIsecret: '$(vkey)'
    fileToScan: '$(System.DefaultWorkingDirectory)/target/verademo.war)' 
   