trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y nodejs
    sudo apt-get install -y npm
    node --version
    npm --version
  displayName: 'Install Node.js and npm'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm test
  displayName: 'Run tests'
