trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    /usr/local/bin/npm install
  displayName: 'Install dependencies'

- script: |
    /usr/local/bin/npm test
  displayName: 'Run tests'
